insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (101,'SNAP','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (102,'SNAP','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (103,'SNAP','Denied','High Salary Income');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (104,'SNAP','Denied','High Rent Income');

insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (105,'CCAP','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (106,'CCAP','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (107,'CCAP','Denied','Kids Not Available');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (108,'CCAP','Denied','eKids Age Above 16 Years');


insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (109,'Medicaid','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (110,'Medicaid','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (111,'Medicaid','Denied','High Income');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (112,'Medicaid','Denied','High Property Income');


insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (113,'Medicare','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (114,'Medicare','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (115,'Medicare','Denied','High Income');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (116,'Medicare','Denied','Age Not Matching');


insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (117,'QHP','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (118,'QHP','Approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (119,'QHP','Denied','expired');
insert into ELIGIBILITY_DTLS (PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (120,'QHP','Denied','expired');